version: '3.8'

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build:
        context: .
    volumes:
      - ./cache:/var/www/html/lib/business-ru/business-online-sdk-php/src/cache
