services:
  web:
    image: nginx:latest
    ports:
      - "${PORT:-80}:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    restart: unless-stopped

  php:
    build:
        context: .
    env_file: .env
    volumes:
      - ./storage/cache:/var/www/html/lib/business-ru/business-online-sdk-php/src/cache
    restart: unless-stopped
